version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: vectordb_tests
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./htmlcov:/app/htmlcov
    environment:
      - PYTHONPATH=/app
      - COHERE_API_KEY=${COHERE_API_KEY:-test_key_for_mocking}
      - ENVIRONMENT=test
    command: >
      sh -c "
        echo 'Running all tests...' &&
        pytest --verbose --cov=src --cov-report=term-missing --cov-report=html &&
        echo 'Tests completed! Coverage report generated in htmlcov/'
      "

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: vectordb_unit_tests
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
      - COHERE_API_KEY=${COHERE_API_KEY:-test_key_for_mocking}
    command: >
      sh -c "
        echo 'Running unit tests...' &&
        pytest -m unit --verbose
      "

  test-integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: vectordb_integration_tests
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
      - COHERE_API_KEY=${COHERE_API_KEY:-test_key_for_mocking}
    command: >
      sh -c "
        echo 'Running integration tests...' &&
        pytest -m integration --verbose
      "

  test-watch:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: vectordb_test_watch
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
      - COHERE_API_KEY=${COHERE_API_KEY:-test_key_for_mocking}
    command: >
      sh -c "
        pip install pytest-watch &&
        ptw --verbose
      "
