services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-db-backend
    ports:
      - "8000:8000"
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - APP_NAME=Vector Database API
      - APP_VERSION=1.0.0
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - STORAGE_TYPE=disk
      - STORAGE_PATH=/app/data
      - STORAGE_FORMAT=json
      - DEFAULT_INDEX_TYPE=brute_force
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - vector-db-network

networks:
  vector-db-network:
    driver: bridge
